#define FORK1_STR " has taken a fork (1/2)\n"
#define FORK2_STR " has taken a fork (2/2)\n"
#define DIE_STR " has died\n"
#define EAT_STR " is eating\n"
#define SLEEP_STR " is sleeping\n"
#define THINK_STR " is thinking\n"
